version: '3.4'

networks:
  default:
    driver: bridge
services:
  api:
    build: ./api
    networks:
      - default
    volumes:
      - ./api/app/:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    ports:
    - "5000:5000"
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
    - "5432:5432"

  front:
    build: ./front
    networks:
      - default
    restart: always
    command: ["python","/app/main.py"]
    ports:
      - "8050:8050"
    volumes:
      - ./front/app:/app
    environment:
      FLASK_ENV: development